
# To skip builds use [ci ckip] in GIT commit-msg

language: node_js
dist: trusty
#dist: xenial

node_js:
  # Note: selenium-webdriver does not support node <4. Would need to degrade tests.
  #- "0.12"
  # Note: >=4 seems to be working like 6.0
  #- "4.4"
  #- "5.11"
  #- "6.12"
  #- "8.9"
  #- "11"
  - "12"
  #- "13"
  - "14"
  # [2020-12-16] sqlite3 compile explodes; - "15"
  - "lts/*"
  # [2020-12-16] sqlite3 compile explodes; - "node"

addons:
  apt:
    packages:
      - python-docutils
      - graphviz
  firefox: "71.0"

before_install:
  - nvm list

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar"
  - "java -jar selenium-server-standalone-2.53.0.jar > /dev/null &"
  - sleep 3
  - test -x "$(which rst2html)" || { mkdir ~/bin && cd ~/bin && ln -s $(which rst2html.py) rst2html; }
  - rst2html --version

script:
  - ./configure
  - ./node_modules/.bin/grunt exec:config_sites
  - npm run test-tap | tee mocha-results.tap

after_script:
  - . ./tools/publish-tap.sh

env:
  - NODE_ENV=testing PATH=/usr/local/bin:$HOME/bin:$PATH

#branches:
#  only:
#   - master
#   - /^test.*$/
#   - /^feature.*$/
#   - /^r[0-9].*$/

notifications:
  email:
    on_success: never
