
# To skip builds use [ci ckip] in GIT commit-msg
language: node_js

node_js:
  #- "0.12"
  - "4.4"
  - "6.1"

addons:
  apt:
    packages:
      - python-docutils
      - graphviz
  firefox: "45"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar"
  - "java -jar selenium-server-standalone-2.53.0.jar > /dev/null &"
  - sleep 3
  - test -x "$(which rst2html)" || { mkdir ~/bin && cd ~/bin && ln -s $(which rst2html.py) rst2html; }
  - rst2html --version

env:
  - NODE_ENV=testing PATH=/usr/local/bin:$HOME/bin:$PATH ENV=testing

#branches:
#  only:
#   - master
#   - /^test.*$/
#   - /^feature.*$/
#   - /^r[0-9].*$/

notifications:
  email:
    on_success: never

