
language: node_js

node_js:
  - "0.12"

before_script:
- echo PATH=$PATH
- rst2html --version
- alias rst2html.py=rst2html && rst2html.py --version
#- rst2html.py --version

addons:
  apt:
    packages:
      - python-docutils

branches:
  not:
  - staging_git_versioning
#  only:
#  - test

env:
#  - NODE_ENV=
  - NODE_ENV=testing PATH=/usr/local/bin:$PATH
#  - NODE_ENV=production

