
# To skip builds use [ci ckip] in GIT commit-msg
language: node_js

node_js:
  # Note: selenium-webdriver does not support node <4. Would need to degrade tests.
  #- "0.12" # see #666.1 failed
  # Note: >=4 seems to be working like 6.0
  - "4.4"
  #- "5.11"
  - "6.1"

addons:
  apt:
    packages:
      - python-docutils
      - graphviz
  firefox: '45'

before_install:
  - npm install -g bower

before_script:
  - scriptname=travis:before-script
  - . ./tools/sh/init.sh
  - . ./tools/sh/env.sh
  - . ./tools/ci/build.sh

env:
  - NODE_ENV=testing PATH=/usr/local/bin:$HOME/bin:$PATH ENV=testing

notifications:
  email:
    on_success: never

deploy:
  - provider: npm
    on:
      tags: true
    api_key:
      secure: Tk2YrZF2+gq1BNO8KR61JW4E4T0U/7/hr5ME+XP8iIgW2IMrljgwLNRfH1tzh/9+7D2Tcybxs5QcJgPwP+aSxvS1GpEwCXPw02TB7xgAtrD7CXB05aBovQc4v4mT6f84rfB50w0LWhG9DuIVX8K7NbDYB0qRhAx90STegii8ols=
