
language: node_js

node_js:
  - "0.12"

addons:
  apt:
    packages:
      - python-docutils

branches:
  not:
  - staging_git_versioning
#  only:
#  - test

env:
#  - NODE_ENV=
  - NODE_ENV=testing
#  - NODE_ENV=production

