
language: node_js

node_js:
  - "0.12"

before_script:
- test -x "$(which rst2html)" || { mkdir ~/bin && cd ~/bin && ln -s $(which rst2html.py) rst2html; }
- rst2html --version

addons:
  apt:
    packages:
      - python-docutils

branches:
  not:
  - staging_git_versioning
  - /^dev.*$/
#  only:
#  - 'master'
#  - 'test.*'
#  - 'feature.*'
#  - 'r[0-9].*'

env:
#  - NODE_ENV=
  - NODE_ENV=testing PATH=/usr/local/bin:$HOME/bin$PATH
#  - NODE_ENV=production

