language: node_js
node_js:
  - "0.10"
  - "0.12"

branches:
  only:
  - master
  - f_sitebuild
  - f_client
  - /^v[0-9]+.[0-9]+.[0-9]+$

env:
  - NODE_ENV=
  - NODE_ENV=testing
#  - NODE_ENV=production

