
# To skip builds use [ci ckip] in GIT commit-msg
language: node_js

node_js:
  - "0.12"
  - "6.0"

before_script:
- test -x "$(which rst2html)" || { mkdir ~/bin && cd ~/bin && ln -s $(which rst2html.py) rst2html; }
- rst2html --version

addons:
  apt:
    packages:
      - python-docutils

branches:
  #only:
  #- master
  #- /^test.*$/
  #- /^feature.*$/
  #- /^r[0-9].*$/
  #not:
  #- staging_git_versioning
  #- dev
  #  # FIXME travis not pattern not working
  #- /^dev.*$/


env:
  - NODE_ENV=testing PATH=/usr/local/bin:$HOME/bin:$PATH ENV=testing

