# git-versioning main: node-sitefile

- type: application/x-project-mpe
  main: node-sitefile
  name: node-sitefile
  version: 0.0.7-dev # node-sitefile
  environments: [ 'development' ]

  pd-meta:
    run:
      cruft: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools"
      tags-scm-sh: "g_f='XXX\\|FIXME\\|TODO';git ls-files|while read f;do grep -n $g_f $f|grep -v 'task.*ignore'|sed 's#^#'\"$f\"'#';done" # tasks:ignore
    init: "sh:./configure grunt:build-test"
    test: "sh:./configure npm:run:test"
    check: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools htd:gitflow-check-doc :git:status grunt:check"
    cruft: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools"

  scripts:
    install:
      - npm run install
    test:
      - NODE_ENV=development npm run test
    mocha-test:
      - NODE_ENV=development npm run mocha-test "$@"
