# git-versioning main: node-sitefile

- type: application/x-project-mpe
  main: node-sitefile
  name: node-sitefile
  version: 0.0.5-dev # node-sitefile
  environments: [ 'development' ]

  pd-meta:
    run:
      cruft: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools"
      behat: "./bin/behat:--tags:~@skip"
      cucumber: "./node_modules/.bin/cucumber-js --compiler coffee:coffee-script/register test/features/"
    init: "sh:./configure grunt:build-test"
    test: "sh:./configure grunt:test ./bin/behat:--tags:~@skip"
    check: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools grunt:check :git:status"
    cruft: "sh:./tools/tags.sh:*.*:bin:config:doc:example:lib:test:tools"

